// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// (Actually manually generated because ffigen failed in env)

import 'dart:ffi' as ffi;

/// Bindings for `src/flutter_spellcheck_hunspell.h`.
class HunspellBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  HunspellBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  HunspellBindings.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
    : _lookup = lookup;

  ffi.Pointer<HunspellHandle> FlutterHunspell_create(ffi.Pointer<ffi.Char> aff_path, ffi.Pointer<ffi.Char> dic_path) {
    return _FlutterHunspell_create(aff_path, dic_path);
  }

  late final _FlutterHunspell_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<HunspellHandle> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>(
        'FlutterHunspell_create',
      );
  late final _FlutterHunspell_create =
      _FlutterHunspell_createPtr.asFunction<
        ffi.Pointer<HunspellHandle> Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  void FlutterHunspell_destroy(ffi.Pointer<HunspellHandle> handle) {
    return _FlutterHunspell_destroy(handle);
  }

  late final _FlutterHunspell_destroyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<HunspellHandle>)>>(
    'FlutterHunspell_destroy',
  );
  late final _FlutterHunspell_destroy =
      _FlutterHunspell_destroyPtr.asFunction<void Function(ffi.Pointer<HunspellHandle>)>();

  int FlutterHunspell_spell(ffi.Pointer<HunspellHandle> handle, ffi.Pointer<ffi.Char> word) {
    return _FlutterHunspell_spell(handle, word);
  }

  late final _FlutterHunspell_spellPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<HunspellHandle>, ffi.Pointer<ffi.Char>)>>(
        'FlutterHunspell_spell',
      );
  late final _FlutterHunspell_spell =
      _FlutterHunspell_spellPtr.asFunction<int Function(ffi.Pointer<HunspellHandle>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Pointer<ffi.Char>> FlutterHunspell_suggest(
    ffi.Pointer<HunspellHandle> handle,
    ffi.Pointer<ffi.Char> word,
    ffi.Pointer<ffi.Int> count,
  ) {
    return _FlutterHunspell_suggest(handle, word, count);
  }

  late final _FlutterHunspell_suggestPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Pointer<ffi.Char>> Function(
            ffi.Pointer<HunspellHandle>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('FlutterHunspell_suggest');
  late final _FlutterHunspell_suggest =
      _FlutterHunspell_suggestPtr.asFunction<
        ffi.Pointer<ffi.Pointer<ffi.Char>> Function(
          ffi.Pointer<HunspellHandle>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  int FlutterHunspell_add(ffi.Pointer<HunspellHandle> handle, ffi.Pointer<ffi.Char> word) {
    return _FlutterHunspell_add(handle, word);
  }

  late final _FlutterHunspell_addPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<HunspellHandle>, ffi.Pointer<ffi.Char>)>>(
        'FlutterHunspell_add',
      );
  late final _FlutterHunspell_add =
      _FlutterHunspell_addPtr.asFunction<int Function(ffi.Pointer<HunspellHandle>, ffi.Pointer<ffi.Char>)>();

  void FlutterHunspell_free_suggestions(
    ffi.Pointer<HunspellHandle> handle,
    ffi.Pointer<ffi.Pointer<ffi.Char>> slist,
    int n,
  ) {
    return _FlutterHunspell_free_suggestions(handle, slist, n);
  }

  late final _FlutterHunspell_free_suggestionsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<HunspellHandle>, ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Int)>
      >('FlutterHunspell_free_suggestions');
  late final _FlutterHunspell_free_suggestions =
      _FlutterHunspell_free_suggestionsPtr.asFunction<
        void Function(ffi.Pointer<HunspellHandle>, ffi.Pointer<ffi.Pointer<ffi.Char>>, int)
      >();
}

final class HunspellHandle extends ffi.Opaque {}
